"""water and weight

Revision ID: 072c562cea86
Revises: cf6681aa294d
Create Date: 2026-10-03 10:13:00.777069
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '072c562cea86'
down_revision: str | None = 'cf6681aa294d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_water_entries_user_id_day', 'water_entries', ['user_id', 'day'], unique=False)
    op.create_table('weight_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_weight_entries_user_id_day')
    )
    op.add_column('users', sa.Column('water_goal_ml', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('water_glass_ml', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'water_glass_ml')
    op.drop_column('users', 'water_goal_ml')
    op.drop_table('weight_entries')
    op.drop_index('ix_water_entries_user_id_day', table_name='water_entries')
    op.drop_table('water_entries')
    # ### end Alembic commands ###
