"""goal profile on users

Revision ID: b4f991b733b0
Revises: 70927c9950b4
Create Date: 2026-10-03 09:49:50.875114
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b4f991b733b0'
down_revision: str | None = '70927c9950b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('activity', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('goal_pace', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('protein_per_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fat_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fat_percent')
    op.drop_column('users', 'protein_per_kg')
    op.drop_column('users', 'goal_pace')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'activity')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
