"""demo accounts

Revision ID: c0976f7302ce
Revises: 75eb9d98340f
Create Date: 2026-10-03 10:46:38.959133
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c0976f7302ce'
down_revision: str | None = '75eb9d98340f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('demo_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'demo_expires_at')
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
