"""meal slots and favourite foods

Revision ID: cf6681aa294d
Revises: b4f991b733b0
Create Date: 2026-10-03 09:55:25.444280
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cf6681aa294d'
down_revision: str | None = 'b4f991b733b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_foods',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'food_id')
    )
    op.add_column('meals', sa.Column('slot', sa.String(length=10), server_default='snack', nullable=False))
    # ### end Alembic commands ###

    # Meals written before slots existed: the clock decides, then the name
    # (services/slots.py does the same for new ones)
    op.execute(
        """
        UPDATE meals SET slot = CASE
            WHEN at IS NOT NULL AND at < '11:00' THEN 'breakfast'
            WHEN at IS NOT NULL AND at < '16:00' THEN 'lunch'
            WHEN at IS NOT NULL AND at < '21:00' THEN 'dinner'
            WHEN at IS NOT NULL THEN 'snack'
            WHEN lower(title) LIKE '%doru%' OR lower(title) LIKE '%breakfast%' THEN 'breakfast'
            WHEN lower(title) LIKE '%ru_ak%' OR lower(title) LIKE '%lunch%' THEN 'lunch'
            WHEN lower(title) LIKE '%ve_er%' OR lower(title) LIKE '%dinner%' THEN 'dinner'
            ELSE 'snack'
        END
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'slot')
    op.drop_table('favourite_foods')
    # ### end Alembic commands ###
